# Generated by Django 2.2.4 on 2019-08-30 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user', models.ManyToManyField(blank=True, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation', models.CharField(choices=[('late_training', 'Sen ankomst till träning'), ('late_notice', 'Sen anmälan om missad träning'), ('late_game', 'Sen ankomst till matchsamling'), ('forgot_gear', 'Glömt material'), ('wrong_gear', 'Felaktiga kläder på träning'), ('stick_cutoff', 'Avslagen klubba'), ('leave_training', 'Lämnat träning'), ('game_penalty', 'Utvisning'), ('shooting_during_brief', 'Skott under genomgång'), ('forgot_shaker', 'Glömt skakers'), ('pic_in_media', 'Bild i MVT/Corren'), ('interview', 'Intervju i MVT/Corren'), ('video_interview', 'Intervju i MVT/Corren'), ('interview_bollius', 'Intervjuad av Bollius'), ('front_page', 'Framsida i tidningen'), ('pic_nationwide_media', 'Bild i rikstäckande media'), ('interview_nationwide_media', 'Intervju i rikstäckande media')], default=0, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.Player')),
            ],
        ),
    ]
