# Generated by Django 2.2.4 on 2019-09-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
    ]
